name: Build CosEvm
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
    name: cosevm ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: "stable"
          check-latest: true
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile cosevm
        run: |
          go mod download
          cd cmd/cosevmd
          go build .

      - uses: actions/upload-artifact@v4
        with:
          name: cosevmd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/cosevmd/cosevmd
